/* eslint-disable no-alert, no-console */
// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AppButton: typeof import('./src/components/app-list/app-button.vue')['default']
    AppData: typeof import('./src/components/app-data/app-data.vue')['default']
    AppList: typeof import('./src/components/app-list/app-list.vue')['default']
    AppNav: typeof import('./src/components/app-nav/app-nav.vue')['default']
    UserData: typeof import('./src/components/user-data/user-data.vue')['default']
  }
}

export { }
